version: "3.7"

services:
  db:
    image: "mongo:latest"
    ports:
      - 27017:27017
  api:
    build: "."
    ports:
      - 8080:8080
    environment:
      MONGO_DB_URI: mongodb://db:27017
      PORT: 8080
    depends_on:
      - db
    restart: on-failure